spring:
  application:
    name: ws
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 172.17.179.154
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 100
    password: pHjo70qjIroztPHR
server:
  port: 7773

sso:
  app: ws
  exclude-login-path-patterns: /api/auth/** # /api/open/**
  exclude-multipoint-login-path-patterns: /api/auth/**,/actuator/**   #/api/open/**
  expired: 3600

management:
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
    health:
      show-details: always

mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml
  type-aliases-package: com.lj.iot.biz.db.*.entity,com.lj.iot.common.system.entity
  global-config:
    db-config:
      id-type: auto

logging:
  baseUrl: ''
  file:
    name: ${logging.baseUrl}logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 1GB
      file-name-pattern: ${logging.baseUrl}logs/${spring.application.name}-%d{yyyy-MM-dd}.%i.log
      max-history: 10
  level:
    io:
      netty:
        channel:
          DefaultChannelPipeline: info
ws:
  port: 7779
  keep-alive-interval: 1000